import type { Metadata } from 'next'
import Header from '../components/Header'
import Prompt from '../components/promptinput'
import '../styles/golbal.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* header */}
        <Header/>
        {/* prompt */}
         <Prompt/>
         {children}
        </body>
    </html>
  )
}
